namespace ServerMonitor.App.Qa.Gallery;

/// <summary>How a token is probed: what the runtime self-check reads back and compares.</summary>
public enum QaTokenKind
{
    /// <summary>A raw <c>SaColor*</c> value. Private to Styles/Tokens/**, so it is read in code, never referenced by XAML.</summary>
    Color,
    Brush,
    Shadow,
    FontFamily,
    Double,
    Style,
    Thickness,
    CornerRadius,
    MotionString
}

/// <summary>One token key and how it is probed.</summary>
public sealed record QaTokenEntry(string Key, QaTokenKind Kind);

/// <summary>
/// QA-ONLY (UI.2 S2, gate F-1). The EXPLICIT list of every <c>Sa*</c> key defined under Styles/Tokens/**
/// (including the theme-dictionary entries), in file order. It is deliberately a literal rather than a scan:
/// <c>QaTokenManifestTests.ManifestMatchesEveryTokenKey</c> fails in both directions (a new token without an
/// entry, or an entry for a removed token), and <c>QaTokenProbePageCoversManifest</c> proves the probe page
/// renders exactly these keys. The runtime self-check (<c>--qa-tokens</c>) resolves each one in Dark, Light and
/// the HighContrast resource simulation. Excluded from Release (see ServerMonitor.App.csproj).
/// </summary>
public static class QaTokenManifest
{
    public static IReadOnlyList<QaTokenEntry> Entries { get; } =
    [
        // Styles/Tokens/Color.Primitives.xaml
        new("SaColorCanvasDark", QaTokenKind.Color),
        new("SaColorCanvasLight", QaTokenKind.Color),
        new("SaColorSurfaceDark", QaTokenKind.Color),
        new("SaColorSurfaceLight", QaTokenKind.Color),
        new("SaColorInteriorDark", QaTokenKind.Color),
        new("SaColorInteriorLight", QaTokenKind.Color),
        new("SaColorTextDark", QaTokenKind.Color),
        new("SaColorTextLight", QaTokenKind.Color),
        new("SaColorTextSecondaryDark", QaTokenKind.Color),
        new("SaColorTextSecondaryLight", QaTokenKind.Color),
        new("SaColorCpuDark", QaTokenKind.Color),
        new("SaColorCpuLight", QaTokenKind.Color),
        new("SaColorMemoryDark", QaTokenKind.Color),
        new("SaColorMemoryLight", QaTokenKind.Color),
        new("SaColorDiskDark", QaTokenKind.Color),
        new("SaColorDiskLight", QaTokenKind.Color),
        new("SaColorAttentionDark", QaTokenKind.Color),
        new("SaColorAttentionLight", QaTokenKind.Color),
        new("SaColorHealthyDark", QaTokenKind.Color),
        new("SaColorHealthyLight", QaTokenKind.Color),
        new("SaColorSuccessDark", QaTokenKind.Color),
        new("SaColorSuccessLight", QaTokenKind.Color),
        new("SaColorErrorDark", QaTokenKind.Color),
        new("SaColorErrorLight", QaTokenKind.Color),
        new("SaColorOfflineDark", QaTokenKind.Color),
        new("SaColorOfflineLight", QaTokenKind.Color),
        new("SaColorBorderNeutralDark", QaTokenKind.Color),
        new("SaColorBorderNeutralLight", QaTokenKind.Color),
        new("SaColorBorderSubtleDark", QaTokenKind.Color),
        new("SaColorBorderSubtleLight", QaTokenKind.Color),
        new("SaColorDividerDark", QaTokenKind.Color),
        new("SaColorDividerLight", QaTokenKind.Color),
        new("SaColorDisabledSurfaceDark", QaTokenKind.Color),
        new("SaColorDisabledSurfaceLight", QaTokenKind.Color),
        new("SaColorDisabledTextDark", QaTokenKind.Color),
        new("SaColorDisabledTextLight", QaTokenKind.Color),
        new("SaColorHoverDark", QaTokenKind.Color),
        new("SaColorHoverLight", QaTokenKind.Color),
        new("SaColorSelectedDark", QaTokenKind.Color),
        new("SaColorSelectedLight", QaTokenKind.Color),
        new("SaColorSelectedTextDark", QaTokenKind.Color),
        new("SaColorSelectedTextLight", QaTokenKind.Color),
        new("SaColorFocusRingDark", QaTokenKind.Color),
        new("SaColorFocusRingLight", QaTokenKind.Color),
        new("SaColorGlassBorderDark", QaTokenKind.Color),
        new("SaColorGlassBorderLight", QaTokenKind.Color),
        new("SaColorGlassHighlightDark", QaTokenKind.Color),
        new("SaColorGlassHighlightLight", QaTokenKind.Color),
        new("SaColorElevatedSurfaceDark", QaTokenKind.Color),
        new("SaColorElevatedSurfaceLight", QaTokenKind.Color),
        new("SaColorGlassTintDark", QaTokenKind.Color),
        new("SaColorGlassTintLight", QaTokenKind.Color),
        new("SaColorSidebarTintDark", QaTokenKind.Color),
        new("SaColorSidebarTintLight", QaTokenKind.Color),
        new("SaColorModalSurfaceDark", QaTokenKind.Color),
        new("SaColorModalSurfaceLight", QaTokenKind.Color),
        new("SaColorOverlaySmokeDark", QaTokenKind.Color),
        new("SaColorOverlaySmokeLight", QaTokenKind.Color),
        // Styles/Tokens/Color.Semantic.xaml
        new("SaCanvasBrush", QaTokenKind.Brush),
        new("SaSurfaceBrush", QaTokenKind.Brush),
        new("SaInteriorBrush", QaTokenKind.Brush),
        new("SaTextBrush", QaTokenKind.Brush),
        new("SaTextSecondaryBrush", QaTokenKind.Brush),
        new("SaCpuBrush", QaTokenKind.Brush),
        new("SaMemoryBrush", QaTokenKind.Brush),
        new("SaDiskBrush", QaTokenKind.Brush),
        new("SaAttentionBrush", QaTokenKind.Brush),
        new("SaHealthyBrush", QaTokenKind.Brush),
        new("SaSuccessBrush", QaTokenKind.Brush),
        new("SaErrorBrush", QaTokenKind.Brush),
        new("SaOfflineBrush", QaTokenKind.Brush),
        new("SaBorderNeutralBrush", QaTokenKind.Brush),
        new("SaBorderSubtleBrush", QaTokenKind.Brush),
        new("SaDividerBrush", QaTokenKind.Brush),
        new("SaDisabledSurfaceBrush", QaTokenKind.Brush),
        new("SaDisabledTextBrush", QaTokenKind.Brush),
        new("SaHoverBrush", QaTokenKind.Brush),
        new("SaSelectedBrush", QaTokenKind.Brush),
        new("SaSelectedTextBrush", QaTokenKind.Brush),
        new("SaFocusRingBrush", QaTokenKind.Brush),
        new("SaHoverTextBrush", QaTokenKind.Brush),
        new("SaBorderInsetBrush", QaTokenKind.Brush),
        new("SaGlassBorderBrush", QaTokenKind.Brush),
        new("SaGlassHighlightBrush", QaTokenKind.Brush),
        // Styles/Tokens/Elevation.xaml
        new("SaNeutralSurfaceBrush", QaTokenKind.Brush),
        new("SaElevatedSurfaceBrush", QaTokenKind.Brush),
        new("SaGlassSurfaceBrush", QaTokenKind.Brush),
        new("SaSidebarMaterialBrush", QaTokenKind.Brush),
        new("SaModalSurfaceBrush", QaTokenKind.Brush),
        new("SaOpaqueFallbackBrush", QaTokenKind.Brush),
        new("SaOverlaySmokeBrush", QaTokenKind.Brush),
        new("SaSurfaceShadow", QaTokenKind.Shadow),
        // Styles/Tokens/Typography.xaml
        new("SaFontDisplay", QaTokenKind.FontFamily),
        new("SaFontText", QaTokenKind.FontFamily),
        new("SaFontMono", QaTokenKind.FontFamily),
        new("SaFontSizeDisplay", QaTokenKind.Double),
        new("SaLineHeightDisplay", QaTokenKind.Double),
        new("SaDisplayTextStyle", QaTokenKind.Style),
        new("SaFontSizeHeading", QaTokenKind.Double),
        new("SaLineHeightHeading", QaTokenKind.Double),
        new("SaHeadingTextStyle", QaTokenKind.Style),
        new("SaFontSizeMetric", QaTokenKind.Double),
        new("SaLineHeightMetric", QaTokenKind.Double),
        new("SaMetricTextStyle", QaTokenKind.Style),
        new("SaFontSizeTitle", QaTokenKind.Double),
        new("SaLineHeightTitle", QaTokenKind.Double),
        new("SaTitleTextStyle", QaTokenKind.Style),
        new("SaFontSizeTitleCompact", QaTokenKind.Double),
        new("SaLineHeightTitleCompact", QaTokenKind.Double),
        new("SaTitleCompactTextStyle", QaTokenKind.Style),
        new("SaFontSizeBody", QaTokenKind.Double),
        new("SaLineHeightBody", QaTokenKind.Double),
        new("SaBodyTextStyle", QaTokenKind.Style),
        new("SaFontSizeCaption", QaTokenKind.Double),
        new("SaLineHeightCaption", QaTokenKind.Double),
        new("SaCaptionTextStyle", QaTokenKind.Style),
        new("SaFontSizeControl", QaTokenKind.Double),
        new("SaLineHeightControl", QaTokenKind.Double),
        new("SaControlTextStyle", QaTokenKind.Style),
        new("SaFontSizeLabel", QaTokenKind.Double),
        new("SaLineHeightLabel", QaTokenKind.Double),
        new("SaLabelTextStyle", QaTokenKind.Style),
        new("SaFontSizeMicro", QaTokenKind.Double),
        new("SaLineHeightMicro", QaTokenKind.Double),
        new("SaMicroTextStyle", QaTokenKind.Style),
        new("SaFontSizeMono", QaTokenKind.Double),
        new("SaLineHeightMono", QaTokenKind.Double),
        new("SaMonoTextStyle", QaTokenKind.Style),
        // Styles/Tokens/Spacing.xaml
        new("SaSpace4", QaTokenKind.Double),
        new("SaSpace8", QaTokenKind.Double),
        new("SaSpace12", QaTokenKind.Double),
        new("SaSpace16", QaTokenKind.Double),
        new("SaSpace24", QaTokenKind.Double),
        new("SaSpace32", QaTokenKind.Double),
        // Styles/Tokens/Radius.xaml
        new("SaRadiusPanel", QaTokenKind.CornerRadius),
        new("SaRadiusCard", QaTokenKind.CornerRadius),
        new("SaRadiusControl", QaTokenKind.CornerRadius),
        new("SaRadiusPill", QaTokenKind.CornerRadius),
        new("SaRadiusMiniBar", QaTokenKind.CornerRadius),
        new("SaRadiusSmall", QaTokenKind.CornerRadius),
        new("SaRadiusHealthSegment", QaTokenKind.CornerRadius),
        // Styles/Tokens/Borders.xaml
        new("SaBorderThickness", QaTokenKind.Thickness),
        new("SaDividerThickness", QaTokenKind.Thickness),
        new("SaFocusRingThickness", QaTokenKind.Thickness),
        // Styles/Tokens/Motion.xaml
        new("SaMotionFocusPeakTime", QaTokenKind.MotionString),
        new("SaMotionFocusFadeEndTime", QaTokenKind.MotionString),
        new("SaMotionFocusReducedHoldTime", QaTokenKind.MotionString),
        new("SaMotionFadeDuration", QaTokenKind.MotionString),
        new("SaMotionFastDuration", QaTokenKind.MotionString),
        new("SaMotionNormalDuration", QaTokenKind.MotionString),
        new("SaMotionSlowDuration", QaTokenKind.MotionString),
        new("SaMotionLinearKeySpline", QaTokenKind.MotionString),
        new("SaMotionDirectKeySpline", QaTokenKind.MotionString),
        new("SaMotionPointToPointKeySpline", QaTokenKind.MotionString),
    ];

    public static IReadOnlyList<string> Keys { get; } = Entries.Select(entry => entry.Key).ToList();
}
