"""Vendors the UI.2 icon set (Boss decision B-1) from a local extract of @hugeicons/core-free-icons.

One-off, reproducible generator - not part of the build. It reads <package>/dist/esm/<Name>Icon.js for exactly the
icons listed below, converts every element into SVG path data (circles become two arcs), joins an icon's elements
into ONE stroke-only path string and writes:

  src/ServerMonitor.App/Styles/Components/Sa.Icons.xaml         x:String SaIcon<Name>Data per icon
  src/ServerMonitor.App/Styles/Components/Icons.manifest.json   provenance per icon (package, version, integrity, licence)

Usage: python tools/ui/vendor-hugeicons.py <path-to-extracted-package-dir>

The package (MIT, Copyright (c) 2025 Hugeicons) is NOT a dependency of the app; only the path data of these icons is
vendored, and THIRD-PARTY-NOTICES.md carries the licence text.
"""
import json
import os
import re
import sys

PACKAGE = "@hugeicons/core-free-icons"
VERSION = "4.3.5"
INTEGRITY = "sha512-Sv+NjHRPnQk+yZsGCMcGznCHdTfJR9PMMOEKcJYAQU4gy90dmlc9PwdtvYOImBZIjiheMsTLL5eMn2DmHxUiUg=="
ICONS = [
    "ServerStack01", "DashboardSquare01", "Clock01", "Settings01", "Refresh", "Add01", "Search01", "ArrowRight01",
    "ArrowDown01", "HardDrive", "Key01", "LockPassword", "Folder01", "Shield01", "View", "InformationCircle",
    "Alert02", "Computer", "Sun03", "Moon02", "Cancel01", "Tick02",
]

ELEMENT = re.compile(r'\["(path|circle)",\s*\{([^}]*)\}\]')
ATTRIBUTE = re.compile(r'(\w+):\s*"([^"]*)"')


def number(value):
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return text if text not in ("-0", "") else "0"


def element_to_path(kind, attributes):
    if kind == "path":
        return attributes["d"]
    cx, cy, r = (float(attributes[k]) for k in ("cx", "cy", "r"))
    left, right = number(cx - r), number(cx + r)
    return (f"M{left} {number(cy)}A{number(r)} {number(r)} 0 1 0 {right} {number(cy)}"
            f"A{number(r)} {number(r)} 0 1 0 {left} {number(cy)}Z")


def main(package_dir):
    repo = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    components = os.path.join(repo, "src", "ServerMonitor.App", "Styles", "Components")
    entries, xaml = [], []
    for name in ICONS:
        source = os.path.join("dist", "esm", f"{name}Icon.js")
        text = open(os.path.join(package_dir, source), encoding="utf-8").read()
        parts = []
        for kind, body in ELEMENT.findall(text):
            attributes = dict(ATTRIBUTE.findall(body))
            if attributes.get("fill", "none") not in ("none", ""):
                raise SystemExit(f"{name}: filled element - the set must be stroke-only")
            if attributes.get("strokeWidth", "1.5") != "1.5":
                raise SystemExit(f"{name}: stroke width {attributes.get('strokeWidth')} is not 1.5")
            parts.append(element_to_path(kind, attributes))
        if not parts:
            raise SystemExit(f"{name}: no path data found")
        data = " ".join(p.strip() for p in parts)
        key = f"SaIcon{name}Data"
        xaml.append(f'    <x:String x:Key="{key}">{data}</x:String>')
        entries.append({"name": name, "key": key, "source": source.replace(os.sep, "/"),
                        "elements": len(parts)})

    manifest = {
        "package": PACKAGE, "version": VERSION, "integrity": INTEGRITY, "license": "MIT",
        "copyright": "Copyright (c) 2025 Hugeicons", "style": "Stroke Rounded (free)", "viewBox": "0 0 24 24",
        "strokeWidth": 1.5, "generator": "tools/ui/vendor-hugeicons.py", "icons": entries,
    }
    with open(os.path.join(components, "Icons.manifest.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    with open(os.path.join(components, "Sa.Icons.xaml"), "w", encoding="utf-8", newline="\n") as f:
        f.write('<ResourceDictionary\n'
                '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"\n'
                '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">\n'
                '    <!-- GENERATED by tools/ui/vendor-hugeicons.py - do not edit by hand. Vendored path data of\n'
                f'         {PACKAGE} {VERSION} (MIT, Copyright (c) 2025 Hugeicons; see THIRD-PARTY-NOTICES.md and\n'
                '         Icons.manifest.json). 24x24 viewBox, stroke-only, drawn by primitives:SaIcon with a 1.5 stroke.\n'
                '         Circles are converted to two arcs; each icon is one path string. -->\n')
        f.write("\n".join(xaml))
        f.write("\n</ResourceDictionary>\n")
    print(f"{len(entries)} icons vendored")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
